
server:
  port: 8002 #服务端口
#spring相关配置
spring:
  application:
    name: jtest-payment #服务名
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.165:3306/jtest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#mybatis:配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.jtest.springcloud.pojo

  #eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      # 所有pojo别名类所在包
  instance:
    #服务名称修改
    instance-id: payment8002
    #访问路径可以显示ip地址
    prefer-ip-address: true